# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Main CI Pipelines

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
      with:
        gradle-version: '8.10.1'

    - name: Build, Test and Scan
      run: ./gradlew build jacocoTestReport --info -- scan
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: thecodemonkey/action-get-gradle-version@master
      id: version

    - run: 'echo version ${{ steps.version.outputs.version }}'

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Unit Test Results
        comment_mode: always
        path: |
          **/build/reports/tests/test/**
          **/build/test-results/tests/*.xml

    - name: Upload IntegrationTest Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        retention-days: 2 day
        path: |
          **/build/test-results/integrationTest/*.xml
          **/build/reports/tests/integrationTest/**

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: unit-test-results
        comment_mode: always
        retention-days: 2 day
        files: "**/build/test-results/test/*.xml"

    - name: Publish Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: Integration Tests Results
        comment_mode: always
        files: "**/build/test-results/integrationTest/*.xml"

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
        generate-branches-badge: true

    - name: Add Coverage PR Comment
      uses: madrapps/jacoco-report@v1.7.1
      with:
        paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        title: Code Coverage Report
        update-comment: true

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: build/reports/jacoco/

  publish:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      packages: write # Needed to push Docker images to GitHub Packages

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Log in to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdi

    - name: Set Short SHA for Docker Image
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

    - name: Logging GitHub SHA and Application version.
      needs: build
      run: echo "GitHub SHA == $GITHUB_SHA_SHORT, application version ==> ${{needs.build.outputs.version}}"

    - name: Build Docker Image
      if: github.ref == 'refs/heads/main'
      run: docker build -t ghcr.io/${{ github.GITHUB_REPOSITORY }}:latest -t ghcr.io/${{ github.GITHUB_REPOSITORY }}:${{GITHUB_SHA_SHORT}}

    - name: Push latest Docker Image to GitHub Packages
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/${{ github.GITHUB_REPOSITORY }}:latest
        docker push ghcr.io/${{ github.GITHUB_REPOSITORY }}:${{GITHUB_SHA_SHORT}}

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
